### ISSUE TITLE
use Geopandas functions to create more standard dataframes

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-prevalence-predictor#13]
Replace the custom `geojson_decoder_1` function calls.

Will simplify collaboration, making it easier for us to follow the logic and the shapes of the data being passed around.

~~This is low priority for now.~~

**Comment by onlyjsmith** [comment]
@ric70x7 @HughSt can we take a look at this now? Currently the function's output has some issues - e.g. it changes the type of `id` from numeric to string, it also removes any additional properties being passed in. We should also check that any `id` being passed in is unique.

I've started (see branch [`feature/geopandas`](https://github.com/disarm-platform/fn-prevalence-predictor/tree/feature/geopandas)), but will need some help - esp making sure it works with the covariate extractor.

**Comment by onlyjsmith** [comment]
@ric70x7 might have found an ok compromise for now - just wondering if you can check it still looks fine to you. It's still on [`feature/geopandas`](https://github.com/disarm-platform/fn-prevalence-predictor/tree/feature/geopandas) branch.

I've mostly worked on the input and output steps, and tried to leave the internal workings alone.

In the future, the ideal might be to get the `disarm-gears` stuff working with GeoPandas - at the moment the `pandas2ri.DataFrame` command crashes because it can't handle a `shapely` object in the `geometry` column of a GeoDataFrame (e.g. [here](https://github.com/disarm-platform/disarm-gears/blob/653fbce7e437d27975f262ed65c21b57339c4770/disarm_gears/r_plugins/r_methods.py#L25))

**Comment by ric70x7** [comment]
@onlyjsmith a few weeks ago Hugh and I were trying to find out why the prevalence predictor was crashing. One of the many things we tried was making the id strings. I don't think that is needed, I think the problem was somewhere else. We just didn't remove that condition as it didn't seem harmful at the moment.

We can keep all the properties of the geojson input if that is needed. So far, the criteria has been to drop anything that is not needed in the handler. A consequence of this criteria is to prefer to use pandas instead of geopandas whenever possible.

**Comment by onlyjsmith** [comment]
Thanks for this, and comment on https://github.com/disarm-platform/disarm-gears/issues/10.

It seems like there's useful question for us here on 'standard' data structures in Python: `pandas` and `geopandas` are the two that we're working with now, but might be more options like something in `numpy`(?).

It might be that the approach in the [feature/geopandas](https://github.com/disarm-platform/fn-prevalence-predictor/tree/feature/geopandas) branch here makes enough sense for now: 
- we don't force any internal libraries to use anything specific, 
- but if we're handling GeoJSON, we use `geopandas` in the layers that interface between your algo code and our infrastructure/wrapper code

Suggest adding this question into the discussions coming in Y2 about the process to packaging algos.

**Comment by onlyjsmith** [comment]
Think is still relevant, but not certain it's a current priority.

Is this causing any problem, or is a more of a _refactor_?

**Comment by HughSt** [comment]
Again OK for icebox as there is no need for deployed `fn-prevalence-predictor`
