### ISSUE TITLE
should the call to fn-covariate-extractor be separate?

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-prevalence-predictor#15]
It's convenient to embed this (`fn-cov-extr`) behaviour inside the `fn-prev-pred` function.

Partially related to https://github.com/disarm-platform/fn-prevalence-predictor/issues/14, but the main point is to keep the functions simpler in what they do - making it easier to reason about them and check their behaviour.

If we took this route, we'd need to create a new way to pipe these two functions together. Some initial options:
- deploy a wrapper function, whose only job is to pipe/wire the `fn-cov-extr` and `fn-prev-pred` functions together
- rely on client-side data processing to join the data together

**Comment by ric70x7** [comment]
I don't have a preference. I just wonder what would be better or more convenient for developing new functions. I'm thinking if at some point we need build longer pipelines...

**Comment by onlyjsmith** [comment]
Close for now - don't think there's a strong-enough need for this use-case. Embedding the call to another function works fine for now. 
Only thing we should do is add a note to the README.

**Comment by onlyjsmith** [comment]
Edited README https://github.com/disarm-platform/fn-prevalence-predictor/commit/759267a7f675c4da826e86456d9b62595de01ffd
