### ISSUE TITLE
add more param checkers

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-prevalence-predictor#7]
Especially need to check that the incoming _geodata_ is in the right format, and that e.g. if properties are required for every point, then we check them.

**Comment by HughSt** [comment]
As I have now written this as an R function in the disarmr package, there is a) no urgency to work on this deployed version and b) maybe a need to add these checkers to the function in the package. Would be good to discuss more generally how to handle this issue about where to focus effort.
